### ISSUE TITLE
toggleClass 2nd argument

### ISSUE THREAD

**Issue by dawidkowalik** [hexydec/dabby#3]
In jquery toggleClass can take a second argument - boolean, which value is used to toggle class - even if it doesn't change anything. I see it implemented in the readme but seems to be not working.

`
$.fn.toggleClassDefault = $.fn.toggleClass;

$.fn.toggleClass = function(selector, value) {
  if (value === true) {
    this.addClass(selector)
  } else if (value === false) {
    this.removeClass(selector)
  } else {
    this.toggleClassDefault(selector)
  }
}`
works as temporary fix

**Comment by hexydec** [comment]
Should be sorted now. Pull latest build for update.
