### ISSUE TITLE
css('value', '') doesn't reset the value

### ISSUE THREAD

**Issue by wafel34** [hexydec/dabby#5]
When using css() function in jquery, giving empty value will reset the inline style.
For example: <div style="maring-top: 10px"></div>
$(div).css('margin-top', '') would result in <div style=""></div>

In dabby, the value isn't removed. Is this a desirable behavior?

Thanks,

**Comment by hexydec** [comment]
Yes that is the desired behaviour. As per the jQuery documentation:

> Setting the value of a style property to an empty string — e.g. `$( "#mydiv" ).css( "color", "")` — removes that property from an element if it has already been directly applied

**Comment by hexydec** [comment]
After a little more digging you are correct, this is a bug. I ahve now updated the code.
