### ISSUE TITLE
.closest() not working in IE11

### ISSUE THREAD

**Issue by wafel34** [hexydec/dabby#6]
Hi,

Looks like .closest() isn't working in IE11. Is this feature supported?
Works in Chrome.

Thanks,

**Comment by hexydec** [comment]
Can you please provide a code sample to show it not working?

**Comment by wafel34** [comment]
Sorry, didn't have much time to check the source in my current project. But when in created a new on, and imported the full library, everything seems to be working, so I probably missing some imports. I solved it through workaround. Sorry for the trouble.
