### ISSUE TITLE
How can I parse html that includes javascript code

### ISSUE THREAD

**Issue by cacuestai** [hexydec/dabby#7]
Hello:

$(selector).load(url[, success]), does not parse the referenced scripts of the form <script src="../script.js"></script> as jQuery does. Would it be possible to include this functionality?

Thank you very much for your attention.

Carlos

**Comment by hexydec** [comment]
Thank you for your bug report, indeed it should execute any scripts in the inserted HTML. Please download the latest code to resolve this issue, and reopen this issue if it is still not working.
